language: ruby
rvm:
- 2.1
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: KeEd7x4OYegti0UWRr147njGftCFENxeupX9aiXN9HeTc+usltPxQp0csITyvdMuLwCK+nlCyDAN8vdwGb+9s5tgyf0ntMzX95R5o8iu1Jokd1EP8Q3pvo8ZenSC5XgO6b2XxSyM8tib1o17lRplDC1lRqQ2rUPxQ6j1I0NFWeviZSbXF57OngANoLBd3LawGLreUyfx+izssTGBZLlnCheUYBxnm+cXyurhC8GEddfqjjaXqUbxZG3HxW4KvByszpJ60CZHXDk5Dm0hdB3rLf0okn+0hldjJgcaNAAZMdd/4IDCsa0sBvF69RQnC3BcQyfkOKIc5ysZKZIvznRK2gg8Hsi4zGo3KlEuRvJJPhwxSeBAMQDmRWDQqauRtKO17rQ+IR1NEbQrkcBJJCSkH97IyTZK4r2MU39hAiMP56SV77Ylij2ihEIBZNnDOaf3thTErfMHPfVHsSIRVmx3c551Z1vsvIEJtRqTMaXEP1gQKPzrsJCVyMAzXk8OMHfC/fSUP+/Q3no/ruy30U+VrLga+TiQJIHqDRgyLfdt4v/AfqlUlxJTk8rRdm5UnYP4l9kEqsUxxJ2c5AdBQ89gFpUxKekAwncL2Q3p2yIlrWgu3vzb0prJw/llikc6e+X+SDe1jEcq+9EvMnf66tJT2TJtyZHvCFyx2a1CwkPAgQs=
  - GH_REF: github.com/entrylabs/entry-hw-docs.git
  - GH_REPO: https://github.com/entrylabs/entry-hw-docs.git
branches:
  only:
    - master
before_script:
  - chmod +x ./script/cibuild
  - chmod +x ./script/cideploy
script:
  - "./script/cibuild"
  - "./script/cideploy"


