# Dependencies
markdown:             kramdown
kramdown:
  input:              GFM
  syntax_highlighter: rouge

# Permalinks
permalink:            pretty

# Setup
title:                Entry Docs
tagline:              'Entry Hardware'
description:          '엔트리 하드웨어 개발 가이드'
url:                  http://entrylabs.github.io
baseurl:              /entry-hw/
imageurl:             /entry-hw/public/image/
base-link-url:        /entry-hw

author:
  name:               'kimorkim'
  url:                http://www.play-entry.org

github:
  repo: 		          https://github.com/entrylabs/entry-hw

paginate:             5
paginate_path:        "/posts/page:num/"

# Custom vars
version:              1.5.2

# Gems
gems: [jekyll-paginate, jekyll-gist]

exclude: [vendor]